export const GET_CUSTOMER_SERVICES = 'GET_CUSTOMER_SERVICES';
export const GET_SERVICE_SUMMARY = 'GET_SERVICE_SUMMARY';
export const ADD_CUSTOMER_SERVICE = 'ADD_CUSTOMER_SERVICE';
export const UPDATE_CUSTOMER_SERVICE = 'UPDATE_CUSTOMER_SERVICE';
export const DELETE_CUSTOMER_SERVICE = 'DELETE_CUSTOMER_SERVICE';
export const CUSTOMER_SERVICE_ERROR = 'CUSTOMER_SERVICE_ERROR';
export const CLEAR_CUSTOMER_SERVICE = 'CLEAR_CUSTOMER_SERVICE';
export const SET_LOADING = 'SET_LOADING';