// Equipment Types
export const GET_EQUIPMENT = 'GET_EQUIPMENT';
export const GET_EQUIPMENT_DETAIL = 'GET_EQUIPMENT_DETAIL';
export const ADD_EQUIPMENT = 'ADD_EQUIPMENT';
export const UPDATE_EQUIPMENT = 'UPDATE_EQUIPMENT';
export const DELETE_EQUIPMENT = 'DELETE_EQUIPMENT';
export const EQUIPMENT_ERROR = 'EQUIPMENT_ERROR';
export const CLEAR_EQUIPMENT = 'CLEAR_EQUIPMENT';
export const SET_LOADING = 'SET_LOADING';
export const FILTER_EQUIPMENT = 'FILTER_EQUIPMENT';
export const CLEAR_FILTER = 'CLEAR_FILTER';

// Maintenance Types
export const GET_MAINTENANCE = 'GET_MAINTENANCE';
export const GET_MAINTENANCE_DETAIL = 'GET_MAINTENANCE_DETAIL';
export const GET_EQUIPMENT_MAINTENANCE = 'GET_EQUIPMENT_MAINTENANCE';
export const ADD_MAINTENANCE = 'ADD_MAINTENANCE';
export const UPDATE_MAINTENANCE = 'UPDATE_MAINTENANCE';
export const DELETE_MAINTENANCE = 'DELETE_MAINTENANCE';
export const MAINTENANCE_ERROR = 'MAINTENANCE_ERROR';
export const CLEAR_MAINTENANCE = 'CLEAR_MAINTENANCE';
export const GET_UPCOMING_MAINTENANCE = 'GET_UPCOMING_MAINTENANCE';
export const GET_OVERDUE_MAINTENANCE = 'GET_OVERDUE_MAINTENANCE';