// frontend/src/contexts/report/types.js
export const GET_CUSTOMER_REGISTRATION_STATS = 'GET_CUSTOMER_REGISTRATION_STATS';
export const GET_SERVICE_REGISTRATION_STATS = 'GET_SERVICE_REGISTRATION_STATS';
export const REPORT_ERROR = 'REPORT_ERROR';
export const CLEAR_REPORT = 'CLEAR_REPORT';
export const SET_LOADING = 'SET_LOADING';