export const GET_SCHEDULE = 'GET_SCHEDULE';
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
export const ADD_SCHEDULE_ITEM = 'ADD_SCHEDULE_ITEM';
export const DELETE_SCHEDULE_ITEM = 'DELETE_SCHEDULE_ITEM';
export const SCHEDULE_ERROR = 'SCHEDULE_ERROR';
export const CLEAR_SCHEDULE = 'CLEAR_SCHEDULE';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';