// Service types
export const GET_SERVICES = 'GET_SERVICES';
export const GET_SERVICE = 'GET_SERVICE';
export const ADD_SERVICE = 'ADD_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const SERVICE_ERROR = 'SERVICE_ERROR';
export const CLEAR_SERVICE = 'CLEAR_SERVICE';

// Service Registration types
export const GET_REGISTRATIONS = 'GET_REGISTRATIONS';
export const GET_MY_REGISTRATIONS = 'GET_MY_REGISTRATIONS';
export const GET_TRAINER_REGISTRATIONS = 'GET_TRAINER_REGISTRATIONS';
export const GET_REGISTRATION = 'GET_REGISTRATION';
export const CREATE_REGISTRATION = 'CREATE_REGISTRATION';
export const UPDATE_REGISTRATION_STATUS = 'UPDATE_REGISTRATION_STATUS';
export const UPDATE_COMPLETED_SESSIONS = 'UPDATE_COMPLETED_SESSIONS';
export const CANCEL_REGISTRATION = 'CANCEL_REGISTRATION';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const CLEAR_REGISTRATION = 'CLEAR_REGISTRATION';

// Common
export const SET_LOADING = 'SET_LOADING';